[package]
name = "veriflow"
description = "VERIFLOW : gestion des rushes audio et vidéo"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "veriflow_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
veriflow-core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
